### ISSUE TITLE
how to remove x86_64 , i386 from Razorpay.framework

### ISSUE THREAD

**Issue by vuevrn** [razorpay/razorpay-ios-sample-app#7]
hi , 
your framework working fine in development mode , 
i go throw with documentation link .
i drag  and drop Razorpay.framework in my application and setup all required things .

now i m on stag to upload application to apple store . during upload i m getting error because of Razorpay.framework  
 
![screen shot 2018-03-31 at 11 08 48 pm](https://user-images.githubusercontent.com/10462847/38165983-c6c45756-3539-11e8-8c26-fc7783403eaa.png)

**Comment by AbhinavArora95** [comment]
When a framework is distributed, it contains architectures of the simulators so that the consumer of the framework can build it on a simulator. However, when you are uploading the archive on itunes, you have to strip these architectures. If you would have been using cocoapods, it would have been done by it. Since, probably you are not using it, please run the attached script on the Razorpay.framework within your archive or before create the archive.
[StripInvalidArchitectures.txt](https://github.com/razorpay/razorpay-ios-sample-app/files/1867791/StripInvalidArchitectures.txt)
